#include <iostream>
#include <string>
#include <vector>

#include "NormalData.h"

using namespace std;

class Solution {
public:
    vector<int> findPermutation(string s) {
        vector<int> res;

        for (int i = 0; i <= s.size(); ++i) {
            if (i == s.size() || s[i] == 'I') {
                // k consecutive D, we need to reverse number from [i, i + k]
                for (int j = i + 1, lenTmp = res.size(); j > lenTmp; --j) {
                    res.push_back(j);
                }
            }
        }

        return res;
    }

    vector<int> findPermutation2(string s) {
        vector<int> res;
        // pushing the right value is tricky
        int up = s.size() + 1;

        for (int i = s.size() - 1; i >= 0; --i) {
            if (s[i] == 'I') {
                res.push_back(up--);
            }
            else
            {
                int count = 1;

                while (i >= 0 && s[i] == 'D') {
                    count++;
                    up--;
                    i--;
                }

                up--;

                for (int j = 0; j < count; ++j) {
                    res.push_back(j + up + 1);
                }
            }
        }

        // be careful about this
        if (up == 1)
            res.push_back(up);

        std::reverse(res.begin(), res.end());
        return res;
    }

    vector<int> findPermutation1(string s) {
        vector<int> res;
        findPermutation1(res, s, s.size() + 1);
        std::reverse(res.begin(), res.end());
        return res;
    }

    void findPermutation1(vector<int> &res, string &s, int up) {
        if (up <= 0)
            return;
        else if (up == 1) {
            res.push_back(1);
        }
        else if (s[up - 2] == 'I') { 
            res.push_back(up--);
            findPermutation1(res, s, up);
        }
        else
        {
            int count = 1;

            while (up >= 2 && s[up - 2] == 'D') {
                count++;
                up--;
            }

            up--;

            for (int i = 0; i < count; ++i) {
                res.push_back(i + up + 1);
            }

            findPermutation1(res, s, up);
        }
    }
};

int main()
{
    Solution sln;
    //string s("I");
    //string s("D");
    //string s("II");
    //string s("DD");
    //string s("III");
    //string s("DDD");
    //string s("ID");
    //string s("DI");
    //string s("IDI");
    //string s("DID");
    //string s("IDD");
    //string s("DII");
    //string s("DIDI");
    //string s("IDID");
    string s("IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIDIIIIIIIIIIIIIDIIIIIIDIIIIIIIIIIIDIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIDIIIIIIIIIIIIIIIIIIIIDIDIIIIDIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIDIIIIIIDIIIIIIIIIIIIIIIIIIDIIDIIIIIIDIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIDDIIIIIIIIIIIIIDIIIIIIIIIIIIIDIDIDIDIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIDIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIDIIDIIIIIIIIIIIIIIIIDIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIDIIIIIIIIIIIIIIIIIIIIIIIDIIIDIIIIIIIIIDIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIDIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIDIIIIIIIIIIIIDDIIIIIDIIIIIIIIDDIIIIIIIIIIIIIIDIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIDIDIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIDIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIDIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIDIIDIIIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIDIIIIIIIIIIIIDIIIIIDIIDIIIIIIIIIIDIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIDIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIIDIIIIIIIIIIIIIIIIIIIDIIIDIIIIDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIDIIIIIDIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIDIIIIIIIIIIIIIIDDIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIDIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIDIIIIIIDIIIIIIIIIIIIIDDIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIDIIIIIIIIIIIIDIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIDIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIDIIDIIIIIDIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIIIIIDIDDDIIIDDIIIIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIDIIIIIDIIIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIDIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIDIIDIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIDIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIDIIIIIIDIIDIIIIIIIIIIIIIIDIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIDIIIIIIIIIIDIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIDIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIDDIIDIIIIIIIDDIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIDIIIIIIIDIIIIIIIDIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIDIIIIIIIIIDIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIDIIIIIIIIIIDIIIIIIIIIIIIIDIIIIIIDDIIIDIIIIIIIIDIDIIIIIDIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIDIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIDIIIIDIDIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIDIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIDIIIIIDIIIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIDIIIIIIIIIIIDIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIDIIIIIIIIDIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIDIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIDIIIDIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIDIIIIIIIIIIDIDIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIDDIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIDIIIIIIIDIIIDIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIDIIIIIDIIIIIIIIIIIDIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIDIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIDIIIIIIIIDIIDIDIDIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIDIIDIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIDIIIIDIIIIIIIIIDIIDIIIIIDIIIIIIDIIDIIIIIIIIIIIIIDIIIIIIDIIIIIIDIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIDIIIIDIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDDIIIIIIIDIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIDIIIDIIIIIIIIIIIIIIIDIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIDIDIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDDIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIDIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIDDIIIIIIIDIIIIIIDIIIDIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDDIIIIIIIIIDIIIIIIIIIDIIIIIIIIIIIDIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIDIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIDIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDDIIIIIIIIIIIIIIIIIIIDIIDIIIIIIIIIIIIIIDIIIIIIIIIIIDDIIIIIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIDIIDIIIIIIIIIIIIDIIIIIIDIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIDIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIDIIIIIIIIIIIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDIIIIIIIIIIIDIIIIIDIIDIIIIIIDIIIIIIIIIIIDIIIIIIIDIIIIIIIIIDIIDIIIIDIIIIIIIIIIII");
    vector<int> res = sln.findPermutation(s);
    printVector<int>(res);
    return 0;
}
